name: podo-production
services:
  - name: frontend
    source_dir: /
    github:
      repo: cottrellashley/podo
      branch: main
    build_command: npm ci && npm run build
    run_command: npx serve -s dist -l 8080 --host 0.0.0.0
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    type: service
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: /api
        
  - name: backend
    source_dir: /server
    github:
      repo: cottrellashley/podo
      branch: main
    build_command: npm ci --only=production
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    type: service
    http_port: 3001
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        type: SECRET
        value: your-super-secure-jwt-secret-change-this
      - key: CORS_ORIGINS
        value: ${_self.PUBLIC_URL}
      - key: DATABASE_URL
        value: ${podo-db.DATABASE_URL}
      - key: PORT
        value: "3001"
    health_check:
      http_path: /api/health
      
databases:
  - name: podo-db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1 